spring:
  application:
     name: ConfigServerDemo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shalini06mittal/CloudConfigRepo.git
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8888

#spring.cloud.config.server.git.uri=https://github.com/shalini06mittal/CloudConfigRepo.git
#  spring.rabbitmq.host=localhost
#  spring.rabbitmq.port=5672
#  spring.rabbitmq.username=guest
#  spring.rabbitmq.password=guest
