spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
#      routes:
#        - id: ACCOUNTS
#          uri: lb://ACCOUNTS
#          predicates:
#            - Path=/api/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:9091/realms/ms-oauth/protocol/openid-connect/certs"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    root: INFO
    com:
      gateway:
        GatewayServerDemo: DEBUG
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinitionRouteLocator: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 5s